#!/bin/bash
# onebusaway-uk-network-rail-gtfs-realtime	This shell script starts and stops the
#   OneBusAway Network Rail GTFS-realtime application
#
# chkconfig: 345 75 25
# description: onebusaway-uk-network-rail-gtfs-realtime - An application for
#   generating a GTFS-realtime feed for Network Rail realtime data.
# pidfile: /var/run/onebusaway-uk-network-rail-gtfs-realtime.pid
# config: /etc/onebusaway-uk-network-rail-gtfs-realtime/onebusaway-uk-network-rail-gtfs-realtime.conf
### BEGIN INIT INFO
# Provides: onebusaway-uk-network-rail-gtfs-realtime
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Description: OneBusAway Network Rail GTFS-realtime application
# Short-Description: start and stop onebusaway-uk-network-rail-gtfs-realtime
### END INIT INFO
#
#

if [ -r /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
else
    exit 1
fi

NAME="$(basename $0)"
unset ISBOOT
if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
    NAME="${NAME:3}"
    ISBOOT="1"
fi

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser"
else
    SU="su"
fi

# Get the config (use this for environment specific settings)
APPLICATION_CFG="/etc/onebusaway-uk-network-rail-gtfs-realtime/onebusaway-uk-network-rail-gtfs-realtime.conf"
if [ -r "$APPLICATION_CFG" ]; then
    . ${APPLICATION_CFG}
fi

# Get instance specific config file
if [ -r "/etc/sysconfig/${NAME}" ]; then
    . /etc/sysconfig/${NAME}
fi

# Path to the jar
JAR_FILE="${JAR_FILE:-/usr/share/onebusaway-uk-network-rail-gtfs-realtime/onebusaway-uk-network-rail-gtfs-realtime.jar}"

# Define the tomcat username
OBA_USER="${OBA_USER:-root}"
OBA_GROUP="${OBA_GROUP:-root}"

# Define the log file
LOG_FILE="${LOG_FILE:-/var/log/onebusaway-uk-network-rail-gtfs-realtime/onebusaway-uk-network-rail-gtfs-realtime.log}"

# Define the java executable
JAVA="${JAVA:-java}"
JVM_ARGS="${JVM_ARGS:-}"

# Define the PID file
PID_FILE="/var/run/${NAME}.pid"
LOCK_FILE="/var/lock/subsys/${NAME}"

USERNAME="${USERNAME:-}"
PASSWORD="${PASSWORD:-}"
ATOC_TIMETABLE_PATH="${ATOC_TIMETABLE_PATH:-}"

ALL_ARGS="--username=${USERNAME} --password=${PASSWORD} --atocTimetablePath=${ATOC_TIMETABLE_PATH} ${APPLICATION_ARGS}"

# Define the command to launch the application
APPLICATION_CMD="java ${JVM_ARGS} -jar ${JAR_FILE} -daemonize -pidFile ${PID_FILE} -outputFile \"&2\" -errorFile ${LOG_FILE}  ${ALL_ARGS}" 

RETVAL="0"

function checkpid() {
    local i
    for i in $* ; do
        if [ -d "/proc/${i}" ]; then
            return 0
        fi
    done
    return 1
}

# See how we were called.
function start() {
    echo -n "Starting ${NAME}: "
    if [ -f "${LOCK_FILE}" ] ; then
        if [ -f "${PID_FILE}" ]; then
            read kpid < $PID_FILE
                if checkpid $kpid 2>&1; then
                    echo "$NAME process already running"
                        return -1
                    else
                        echo "lock file found but no process running for"
                        echo "pid $kpid, continuing"
                fi
        fi
    fi

    # Make sure the PID file has proper ownership
    touch $PID_FILE
    chown ${OBA_USER} $PID_FILE

    # Make sure the log file has proper ownership
    touch $LOG_FILE
    chown ${OBA_USER}:${OBA_GROUP} $LOG_FILE

    $SU - $OBA_USER -c "${APPLICATION_CMD}" >> $LOG_FILE 2>&1
    RETVAL="$?"
    if [ "$RETVAL" -eq 0 ]; then 
        log_success_msg
        touch $LOCK_FILE
    else
        log_failure_msg
    fi
    #echo
    return $RETVAL
}

function status() {
    RETVAL="1"
    if [ -f "${PID_FILE}" ]; then
        read kpid < $PID_FILE
        if checkpid $kpid 2>&1; then
            echo "$0 is already running (${kpid})"
            RETVAL="0"
        else
            echo "lock file found but no process running for pid $kpid"
        fi
    else
        pid="$(pgrep -u ${OBA_USER} java)"
        if [ -n "$pid" ]; then
            echo "$0 running (${pid}) but no PID file exists"
            RETVAL="0"
        else
            echo "$0 is stopped"
        fi
    fi
    return $RETVAL
}

function stop() {
    echo -n "Stopping $NAME: "
    if [ -f "${LOCK_FILE}" ]; then
        if [ -f "${PID_FILE}" ]; then
            read kpid < $PID_FILE
            kill $kpid
            log_success_msg
        else
            log_failure_msg
        fi
        rm -f $LOCK_FILE $PID_FILE
    else
        log_failure_msg
    fi
    #echo
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2    
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|status|version}"
        exit 1
esac

exit $RETVAL
