//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for an annotated reference to a stop that is defined elsewhere using a StopPointStructure. The annotation is the stop's common name.
 * 
 * <p>Java class for AnnotatedStopPointRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedStopPointRefStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopPointRef" type="{http://www.naptan.org.uk/}AtcoCodeType"/>
 *         &lt;element name="CommonName" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure"/>
 *         &lt;element name="Indicator" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *         &lt;element name="LocalityName" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="LocalityQualifier" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedStopPointRefStructure", propOrder = {
    "stopPointRef",
    "commonName",
    "indicator",
    "localityName",
    "localityQualifier"
})
public class AnnotatedStopPointRefStructure {

    @XmlElement(name = "StopPointRef", required = true)
    protected String stopPointRef;
    @XmlElement(name = "CommonName", required = true)
    protected NaturalLanguageStringStructure commonName;
    @XmlElement(name = "Indicator")
    protected NaturalLanguagePlaceNameStructure indicator;
    @XmlElement(name = "LocalityName")
    protected NaturalLanguageStringStructure localityName;
    @XmlElement(name = "LocalityQualifier")
    protected NaturalLanguageStringStructure localityQualifier;

    /**
     * Gets the value of the stopPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopPointRef() {
        return stopPointRef;
    }

    /**
     * Sets the value of the stopPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopPointRef(String value) {
        this.stopPointRef = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setCommonName(NaturalLanguageStringStructure value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the indicator property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getIndicator() {
        return indicator;
    }

    /**
     * Sets the value of the indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setIndicator(NaturalLanguagePlaceNameStructure value) {
        this.indicator = value;
    }

    /**
     * Gets the value of the localityName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityName() {
        return localityName;
    }

    /**
     * Sets the value of the localityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityName(NaturalLanguageStringStructure value) {
        this.localityName = value;
    }

    /**
     * Gets the value of the localityQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityQualifier() {
        return localityQualifier;
    }

    /**
     * Sets the value of the localityQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityQualifier(NaturalLanguageStringStructure value) {
        this.localityQualifier = value;
    }

}
