//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusStopTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusStopTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="MKD"/>
 *     &lt;enumeration value="marked"/>
 *     &lt;enumeration value="HAR"/>
 *     &lt;enumeration value="hailAndRide"/>
 *     &lt;enumeration value="CUS"/>
 *     &lt;enumeration value="custom"/>
 *     &lt;enumeration value="FLX"/>
 *     &lt;enumeration value="flexible"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusStopTypeEnumeration")
@XmlEnum
public enum BusStopTypeEnumeration {


    /**
     * Marked (pole, shelter etc).
     * 
     */
    MKD("MKD"),
    @XmlEnumValue("marked")
    MARKED("marked"),

    /**
     * Hail and Ride - requires Hail and Ride section.
     * 
     */
    HAR("HAR"),
    @XmlEnumValue("hailAndRide")
    HAIL_AND_RIDE("hailAndRide"),

    /**
     * Custom (unmarked, or only marked on road).
     * 
     */
    CUS("CUS"),
    @XmlEnumValue("custom")
    CUSTOM("custom"),

    /**
     * Flexible zone.
     * 
     */
    FLX("FLX"),
    @XmlEnumValue("flexible")
    FLEXIBLE("flexible");
    private final String value;

    BusStopTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusStopTypeEnumeration fromValue(String v) {
        for (BusStopTypeEnumeration c: BusStopTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
