//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Opening hours 
 * 
 * <p>Java class for DayAndTimeAvailabilityStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DayAndTimeAvailabilityStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="DayTypes">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;group ref="{http://www.naptan.org.uk/}DaysGroup"/>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="Season" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="Spring" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
 *                       &lt;element name="Summer" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
 *                       &lt;element name="Autumn" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
 *                       &lt;element name="Winter" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;element name="HolidayTypes" type="{http://www.naptan.org.uk/}BankHolidaysStructure"/>
 *         &lt;/choice>
 *         &lt;element name="OpeningHours" type="{http://www.naptan.org.uk/}DailyOpeningHoursStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DayAndTimeAvailabilityStructure", propOrder = {
    "dayTypes",
    "season",
    "holidayTypes",
    "openingHours"
})
public class DayAndTimeAvailabilityStructure {

    @XmlElement(name = "DayTypes")
    protected DayAndTimeAvailabilityStructure.DayTypes dayTypes;
    @XmlElement(name = "Season")
    protected DayAndTimeAvailabilityStructure.Season season;
    @XmlElement(name = "HolidayTypes")
    protected BankHolidaysStructure holidayTypes;
    @XmlElement(name = "OpeningHours", required = true)
    protected DailyOpeningHoursStructure openingHours;

    /**
     * Gets the value of the dayTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DayAndTimeAvailabilityStructure.DayTypes }
     *     
     */
    public DayAndTimeAvailabilityStructure.DayTypes getDayTypes() {
        return dayTypes;
    }

    /**
     * Sets the value of the dayTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayAndTimeAvailabilityStructure.DayTypes }
     *     
     */
    public void setDayTypes(DayAndTimeAvailabilityStructure.DayTypes value) {
        this.dayTypes = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link DayAndTimeAvailabilityStructure.Season }
     *     
     */
    public DayAndTimeAvailabilityStructure.Season getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayAndTimeAvailabilityStructure.Season }
     *     
     */
    public void setSeason(DayAndTimeAvailabilityStructure.Season value) {
        this.season = value;
    }

    /**
     * Gets the value of the holidayTypes property.
     * 
     * @return
     *     possible object is
     *     {@link BankHolidaysStructure }
     *     
     */
    public BankHolidaysStructure getHolidayTypes() {
        return holidayTypes;
    }

    /**
     * Sets the value of the holidayTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankHolidaysStructure }
     *     
     */
    public void setHolidayTypes(BankHolidaysStructure value) {
        this.holidayTypes = value;
    }

    /**
     * Gets the value of the openingHours property.
     * 
     * @return
     *     possible object is
     *     {@link DailyOpeningHoursStructure }
     *     
     */
    public DailyOpeningHoursStructure getOpeningHours() {
        return openingHours;
    }

    /**
     * Sets the value of the openingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link DailyOpeningHoursStructure }
     *     
     */
    public void setOpeningHours(DailyOpeningHoursStructure value) {
        this.openingHours = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://www.naptan.org.uk/}DaysGroup"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "mondayToFriday",
        "saturday",
        "notMonday",
        "notTuesday",
        "notWednesday",
        "notThursday",
        "notFriday",
        "notSaturday",
        "mondayToSaturday",
        "sunday",
        "mondayToSunday",
        "weekend"
    })
    public static class DayTypes {

        @XmlElement(name = "Monday")
        protected String monday;
        @XmlElement(name = "Tuesday")
        protected String tuesday;
        @XmlElement(name = "Wednesday")
        protected String wednesday;
        @XmlElement(name = "Thursday")
        protected String thursday;
        @XmlElement(name = "Friday")
        protected String friday;
        @XmlElement(name = "MondayToFriday")
        protected String mondayToFriday;
        @XmlElement(name = "Saturday")
        protected String saturday;
        @XmlElement(name = "NotMonday")
        protected String notMonday;
        @XmlElement(name = "NotTuesday")
        protected String notTuesday;
        @XmlElement(name = "NotWednesday")
        protected String notWednesday;
        @XmlElement(name = "NotThursday")
        protected String notThursday;
        @XmlElement(name = "NotFriday")
        protected String notFriday;
        @XmlElement(name = "NotSaturday")
        protected String notSaturday;
        @XmlElement(name = "MondayToSaturday")
        protected String mondayToSaturday;
        @XmlElement(name = "Sunday")
        protected String sunday;
        @XmlElement(name = "MondayToSunday")
        protected String mondayToSunday;
        @XmlElement(name = "Weekend")
        protected String weekend;

        /**
         * Gets the value of the monday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonday() {
            return monday;
        }

        /**
         * Sets the value of the monday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonday(String value) {
            this.monday = value;
        }

        /**
         * Gets the value of the tuesday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTuesday() {
            return tuesday;
        }

        /**
         * Sets the value of the tuesday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTuesday(String value) {
            this.tuesday = value;
        }

        /**
         * Gets the value of the wednesday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWednesday() {
            return wednesday;
        }

        /**
         * Sets the value of the wednesday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWednesday(String value) {
            this.wednesday = value;
        }

        /**
         * Gets the value of the thursday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThursday() {
            return thursday;
        }

        /**
         * Sets the value of the thursday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThursday(String value) {
            this.thursday = value;
        }

        /**
         * Gets the value of the friday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFriday() {
            return friday;
        }

        /**
         * Sets the value of the friday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFriday(String value) {
            this.friday = value;
        }

        /**
         * Gets the value of the mondayToFriday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMondayToFriday() {
            return mondayToFriday;
        }

        /**
         * Sets the value of the mondayToFriday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMondayToFriday(String value) {
            this.mondayToFriday = value;
        }

        /**
         * Gets the value of the saturday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSaturday() {
            return saturday;
        }

        /**
         * Sets the value of the saturday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSaturday(String value) {
            this.saturday = value;
        }

        /**
         * Gets the value of the notMonday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotMonday() {
            return notMonday;
        }

        /**
         * Sets the value of the notMonday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotMonday(String value) {
            this.notMonday = value;
        }

        /**
         * Gets the value of the notTuesday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotTuesday() {
            return notTuesday;
        }

        /**
         * Sets the value of the notTuesday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotTuesday(String value) {
            this.notTuesday = value;
        }

        /**
         * Gets the value of the notWednesday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotWednesday() {
            return notWednesday;
        }

        /**
         * Sets the value of the notWednesday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotWednesday(String value) {
            this.notWednesday = value;
        }

        /**
         * Gets the value of the notThursday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotThursday() {
            return notThursday;
        }

        /**
         * Sets the value of the notThursday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotThursday(String value) {
            this.notThursday = value;
        }

        /**
         * Gets the value of the notFriday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotFriday() {
            return notFriday;
        }

        /**
         * Sets the value of the notFriday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotFriday(String value) {
            this.notFriday = value;
        }

        /**
         * Gets the value of the notSaturday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotSaturday() {
            return notSaturday;
        }

        /**
         * Sets the value of the notSaturday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotSaturday(String value) {
            this.notSaturday = value;
        }

        /**
         * Gets the value of the mondayToSaturday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMondayToSaturday() {
            return mondayToSaturday;
        }

        /**
         * Sets the value of the mondayToSaturday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMondayToSaturday(String value) {
            this.mondayToSaturday = value;
        }

        /**
         * Gets the value of the sunday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSunday() {
            return sunday;
        }

        /**
         * Sets the value of the sunday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSunday(String value) {
            this.sunday = value;
        }

        /**
         * Gets the value of the mondayToSunday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMondayToSunday() {
            return mondayToSunday;
        }

        /**
         * Sets the value of the mondayToSunday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMondayToSunday(String value) {
            this.mondayToSunday = value;
        }

        /**
         * Gets the value of the weekend property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeekend() {
            return weekend;
        }

        /**
         * Sets the value of the weekend property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeekend(String value) {
            this.weekend = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Spring" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
     *         &lt;element name="Summer" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
     *         &lt;element name="Autumn" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
     *         &lt;element name="Winter" type="{http://www.naptan.org.uk/}EmptyType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "spring",
        "summer",
        "autumn",
        "winter"
    })
    public static class Season {

        @XmlElement(name = "Spring")
        protected String spring;
        @XmlElement(name = "Summer")
        protected String summer;
        @XmlElement(name = "Autumn")
        protected String autumn;
        @XmlElement(name = "Winter")
        protected String winter;

        /**
         * Gets the value of the spring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpring() {
            return spring;
        }

        /**
         * Sets the value of the spring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpring(String value) {
            this.spring = value;
        }

        /**
         * Gets the value of the summer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummer() {
            return summer;
        }

        /**
         * Sets the value of the summer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummer(String value) {
            this.summer = value;
        }

        /**
         * Gets the value of the autumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutumn() {
            return autumn;
        }

        /**
         * Sets the value of the autumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutumn(String value) {
            this.autumn = value;
        }

        /**
         * Gets the value of the winter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWinter() {
            return winter;
        }

        /**
         * Sets the value of the winter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWinter(String value) {
            this.winter = value;
        }

    }

}
