//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * Describes the frequency of a  frequency-based service. 
 * 
 * <p>Java class for FrequencyStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FrequencyStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScheduledFrequency" type="{http://www.naptan.org.uk/}DurationType"/>
 *         &lt;element name="MinimumFrequency" type="{http://www.naptan.org.uk/}DurationType" minOccurs="0"/>
 *         &lt;element name="MaximumFrequency" type="{http://www.naptan.org.uk/}DurationType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FrequencyStructure", propOrder = {
    "scheduledFrequency",
    "minimumFrequency",
    "maximumFrequency",
    "description"
})
public class FrequencyStructure {

    @XmlElement(name = "ScheduledFrequency", required = true)
    protected Duration scheduledFrequency;
    @XmlElement(name = "MinimumFrequency")
    protected Duration minimumFrequency;
    @XmlElement(name = "MaximumFrequency")
    protected Duration maximumFrequency;
    @XmlElement(name = "Description")
    protected NaturalLanguageStringStructure description;

    /**
     * Gets the value of the scheduledFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getScheduledFrequency() {
        return scheduledFrequency;
    }

    /**
     * Sets the value of the scheduledFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setScheduledFrequency(Duration value) {
        this.scheduledFrequency = value;
    }

    /**
     * Gets the value of the minimumFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinimumFrequency() {
        return minimumFrequency;
    }

    /**
     * Sets the value of the minimumFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinimumFrequency(Duration value) {
        this.minimumFrequency = value;
    }

    /**
     * Gets the value of the maximumFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaximumFrequency() {
        return maximumFrequency;
    }

    /**
     * Sets the value of the maximumFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaximumFrequency(Duration value) {
        this.maximumFrequency = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setDescription(NaturalLanguageStringStructure value) {
        this.description = value;
    }

}
