//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationGridTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocationGridTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="UKOS"/>
 *     &lt;enumeration value="IrishOS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocationGridTypeEnumeration")
@XmlEnum
public enum LocationGridTypeEnumeration {


    /**
     * Ordnance Survey UK grid with origin at bottom left of Sheet SV.
     * 
     */
    UKOS("UKOS"),

    /**
     * Ordnance Survey Irish grid with origin at bottom left of Grid V.
     * 
     */
    @XmlEnumValue("IrishOS")
    IRISH_OS("IrishOS");
    private final String value;

    LocationGridTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocationGridTypeEnumeration fromValue(String v) {
        for (LocationGridTypeEnumeration c: LocationGridTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
