//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * @MappingSystem.
 * Identifies the map reference system of Map element IDs (e.g. OSODRs or TOIDs) of any mapping layer references used. 
 * 
 * <p>Java class for MapSystemReferenceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapSystemReferenceStructure">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="MappingSystem" use="required" type="{http://www.naptan.org.uk/}MappingSystemEnumeration" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapSystemReferenceStructure", propOrder = {
    "value"
})
public class MapSystemReferenceStructure {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "MappingSystem", required = true)
    protected MappingSystemEnumeration mappingSystem;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the mappingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link MappingSystemEnumeration }
     *     
     */
    public MappingSystemEnumeration getMappingSystem() {
        return mappingSystem;
    }

    /**
     * Sets the value of the mappingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingSystemEnumeration }
     *     
     */
    public void setMappingSystem(MappingSystemEnumeration value) {
        this.mappingSystem = value;
    }

}
