//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NptgSourceLocalityTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NptgSourceLocalityTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="US"/>
 *     &lt;enumeration value="Pa"/>
 *     &lt;enumeration value="Co"/>
 *     &lt;enumeration value="Lo"/>
 *     &lt;enumeration value="DWD"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="PAR"/>
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="ISL"/>
 *     &lt;enumeration value="Add"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NptgSourceLocalityTypeEnumeration")
@XmlEnum
public enum NptgSourceLocalityTypeEnumeration {


    /**
     * Urban Area in OS data.
     * 
     */
    U("U"),

    /**
     * Urban sub-area in OS data..
     * 
     */
    US("US"),

    /**
     * Parish Ð not Wales.
     * 
     */
    @XmlEnumValue("Pa")
    PA("Pa"),

    /**
     * Community Ð Wales only.
     * 
     */
    @XmlEnumValue("Co")
    CO("Co"),

    /**
     * Other Locality in OS data..
     * 
     */
    @XmlEnumValue("Lo")
    LO("Lo"),

    /**
     * Scottish District Ward Ð Scotland only.
     * 
     */
    DWD("DWD"),

    /**
     * Scottish Locality Ð Scotland only.
     * 
     */
    LOC("LOC"),

    /**
     * Scottish Parish Ð Scotland only.
     * 
     */
    PAR("PAR"),

    /**
     * Scottish Registered Electoral District Ð Scotland only.
     * 
     */
    RED("RED"),

    /**
     * Island
     * 
     */
    ISL("ISL"),

    /**
     * Added 
     * 
     */
    @XmlEnumValue("Add")
    ADD("Add");
    private final String value;

    NptgSourceLocalityTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NptgSourceLocalityTypeEnumeration fromValue(String v) {
        for (NptgSourceLocalityTypeEnumeration c: NptgSourceLocalityTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
