//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.org.naptan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LocationSystem_QNAME = new QName("http://www.naptan.org.uk/", "LocationSystem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.org.naptan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatePatternStructure }
     * 
     */
    public DatePatternStructure createDatePatternStructure() {
        return new DatePatternStructure();
    }

    /**
     * Create an instance of {@link HalfOpenTimeRangeStructure }
     * 
     */
    public HalfOpenTimeRangeStructure createHalfOpenTimeRangeStructure() {
        return new HalfOpenTimeRangeStructure();
    }

    /**
     * Create an instance of {@link ClosedDateRangeStructure }
     * 
     */
    public ClosedDateRangeStructure createClosedDateRangeStructure() {
        return new ClosedDateRangeStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Taxi }
     * 
     */
    public StopClassificationStructure.OnStreet.Taxi createStopClassificationStructureOnStreetTaxi() {
        return new StopClassificationStructure.OnStreet.Taxi();
    }

    /**
     * Create an instance of {@link StopValidityStructure }
     * 
     */
    public StopValidityStructure createStopValidityStructure() {
        return new StopValidityStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach.Bay }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach.Bay createStopClassificationStructureOffStreetBusAndCoachBay() {
        return new StopClassificationStructure.OffStreet.BusAndCoach.Bay();
    }

    /**
     * Create an instance of {@link PlusbusZoneVersionedRefStructure }
     * 
     */
    public PlusbusZoneVersionedRefStructure createPlusbusZoneVersionedRefStructure() {
        return new PlusbusZoneVersionedRefStructure();
    }

    /**
     * Create an instance of {@link WGS84PositionStructure }
     * 
     */
    public WGS84PositionStructure createWGS84PositionStructure() {
        return new WGS84PositionStructure();
    }

    /**
     * Create an instance of {@link ClosedDateRangeCollectionStructure }
     * 
     */
    public ClosedDateRangeCollectionStructure createClosedDateRangeCollectionStructure() {
        return new ClosedDateRangeCollectionStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus.MarkedPoint }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus.MarkedPoint createStopClassificationStructureOnStreetBusMarkedPoint() {
        return new StopClassificationStructure.OnStreet.Bus.MarkedPoint();
    }

    /**
     * Create an instance of {@link RegionRefsStructure }
     * 
     */
    public RegionRefsStructure createRegionRefsStructure() {
        return new RegionRefsStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.Place.Location }
     * 
     */
    public StopPointStructure.Place.Location createStopPointStructurePlaceLocation() {
        return new StopPointStructure.Place.Location();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure }
     * 
     */
    public DayAndTimeAvailabilityStructure createDayAndTimeAvailabilityStructure() {
        return new DayAndTimeAvailabilityStructure();
    }

    /**
     * Create an instance of {@link HailAndRideSectionStructure }
     * 
     */
    public HailAndRideSectionStructure createHailAndRideSectionStructure() {
        return new HailAndRideSectionStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus createStopClassificationStructureOnStreetBus() {
        return new StopClassificationStructure.OnStreet.Bus();
    }

    /**
     * Create an instance of {@link TelephoneContactStructure }
     * 
     */
    public TelephoneContactStructure createTelephoneContactStructure() {
        return new TelephoneContactStructure();
    }

    /**
     * Create an instance of {@link StopPointsStructure }
     * 
     */
    public StopPointsStructure createStopPointsStructure() {
        return new StopPointsStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet }
     * 
     */
    public StopClassificationStructure.OnStreet createStopClassificationStructureOnStreet() {
        return new StopClassificationStructure.OnStreet();
    }

    /**
     * Create an instance of {@link NptgLocalityVersionedRefStructure }
     * 
     */
    public NptgLocalityVersionedRefStructure createNptgLocalityVersionedRefStructure() {
        return new NptgLocalityVersionedRefStructure();
    }

    /**
     * Create an instance of {@link BoundingBoxStructure }
     * 
     */
    public BoundingBoxStructure createBoundingBoxStructure() {
        return new BoundingBoxStructure();
    }

    /**
     * Create an instance of {@link FrequencyStructure }
     * 
     */
    public FrequencyStructure createFrequencyStructure() {
        return new FrequencyStructure();
    }

    /**
     * Create an instance of {@link ModesStructure }
     * 
     */
    public ModesStructure createModesStructure() {
        return new ModesStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.AlternativeDescriptors }
     * 
     */
    public StopPointStructure.AlternativeDescriptors createStopPointStructureAlternativeDescriptors() {
        return new StopPointStructure.AlternativeDescriptors();
    }

    /**
     * Create an instance of {@link AnnotatedClosedDateRangeCollectionStructure }
     * 
     */
    public AnnotatedClosedDateRangeCollectionStructure createAnnotatedClosedDateRangeCollectionStructure() {
        return new AnnotatedClosedDateRangeCollectionStructure();
    }

    /**
     * Create an instance of {@link BearingStructure }
     * 
     */
    public BearingStructure createBearingStructure() {
        return new BearingStructure();
    }

    /**
     * Create an instance of {@link FlexibleZoneStructure }
     * 
     */
    public FlexibleZoneStructure createFlexibleZoneStructure() {
        return new FlexibleZoneStructure();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure.DayTypes }
     * 
     */
    public DayAndTimeAvailabilityStructure.DayTypes createDayAndTimeAvailabilityStructureDayTypes() {
        return new DayAndTimeAvailabilityStructure.DayTypes();
    }

    /**
     * Create an instance of {@link StopPointRefsStructure }
     * 
     */
    public StopPointRefsStructure createStopPointRefsStructure() {
        return new StopPointRefsStructure();
    }

    /**
     * Create an instance of {@link LocationStructure.Translation }
     * 
     */
    public LocationStructure.Translation createLocationStructureTranslation() {
        return new LocationStructure.Translation();
    }

    /**
     * Create an instance of {@link AnnotatedCoachRefStructure }
     * 
     */
    public AnnotatedCoachRefStructure createAnnotatedCoachRefStructure() {
        return new AnnotatedCoachRefStructure();
    }

    /**
     * Create an instance of {@link MapStructure }
     * 
     */
    public MapStructure createMapStructure() {
        return new MapStructure();
    }

    /**
     * Create an instance of {@link AnnotatedClosedDateRangeStructure }
     * 
     */
    public AnnotatedClosedDateRangeStructure createAnnotatedClosedDateRangeStructure() {
        return new AnnotatedClosedDateRangeStructure();
    }

    /**
     * Create an instance of {@link DatePatternStructure.DateRange }
     * 
     */
    public DatePatternStructure.DateRange createDatePatternStructureDateRange() {
        return new DatePatternStructure.DateRange();
    }

    /**
     * Create an instance of {@link StopAreaStructure }
     * 
     */
    public StopAreaStructure createStopAreaStructure() {
        return new StopAreaStructure();
    }

    /**
     * Create an instance of {@link DaysOfOperationStructure }
     * 
     */
    public DaysOfOperationStructure createDaysOfOperationStructure() {
        return new DaysOfOperationStructure();
    }

    /**
     * Create an instance of {@link LocationStructure }
     * 
     */
    public LocationStructure createLocationStructure() {
        return new LocationStructure();
    }

    /**
     * Create an instance of {@link DailyOpeningHoursStructure }
     * 
     */
    public DailyOpeningHoursStructure createDailyOpeningHoursStructure() {
        return new DailyOpeningHoursStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus.UnmarkedPoint }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus.UnmarkedPoint createStopClassificationStructureOnStreetBusUnmarkedPoint() {
        return new StopClassificationStructure.OnStreet.Bus.UnmarkedPoint();
    }

    /**
     * Create an instance of {@link StopValidityStructure.StopValidity }
     * 
     */
    public StopValidityStructure.StopValidity createStopValidityStructureStopValidity() {
        return new StopValidityStructure.StopValidity();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Metro }
     * 
     */
    public StopClassificationStructure.OffStreet.Metro createStopClassificationStructureOffStreetMetro() {
        return new StopClassificationStructure.OffStreet.Metro();
    }

    /**
     * Create an instance of {@link OperatorRefStructure }
     * 
     */
    public OperatorRefStructure createOperatorRefStructure() {
        return new OperatorRefStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach createStopClassificationStructureOffStreetBusAndCoach() {
        return new StopClassificationStructure.OffStreet.BusAndCoach();
    }

    /**
     * Create an instance of {@link BankHolidaysStructure }
     * 
     */
    public BankHolidaysStructure createBankHolidaysStructure() {
        return new BankHolidaysStructure();
    }

    /**
     * Create an instance of {@link PlaceRefStructure }
     * 
     */
    public PlaceRefStructure createPlaceRefStructure() {
        return new PlaceRefStructure();
    }

    /**
     * Create an instance of {@link HalfOpenDateRangeStructure }
     * 
     */
    public HalfOpenDateRangeStructure createHalfOpenDateRangeStructure() {
        return new HalfOpenDateRangeStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure }
     * 
     */
    public StopClassificationStructure createStopClassificationStructure() {
        return new StopClassificationStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet }
     * 
     */
    public StopClassificationStructure.OffStreet createStopClassificationStructureOffStreet() {
        return new StopClassificationStructure.OffStreet();
    }

    /**
     * Create an instance of {@link PlusbusZoneRefsStructure }
     * 
     */
    public PlusbusZoneRefsStructure createPlusbusZoneRefsStructure() {
        return new PlusbusZoneRefsStructure();
    }

    /**
     * Create an instance of {@link OperatorRefsStructure }
     * 
     */
    public OperatorRefsStructure createOperatorRefsStructure() {
        return new OperatorRefsStructure();
    }

    /**
     * Create an instance of {@link DayFrequencyStructure }
     * 
     */
    public DayFrequencyStructure createDayFrequencyStructure() {
        return new DayFrequencyStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaVersionedRefStructure }
     * 
     */
    public AdministrativeAreaVersionedRefStructure createAdministrativeAreaVersionedRefStructure() {
        return new AdministrativeAreaVersionedRefStructure();
    }

    /**
     * Create an instance of {@link LineStringStructure }
     * 
     */
    public LineStringStructure createLineStringStructure() {
        return new LineStringStructure();
    }

    /**
     * Create an instance of {@link StopAreaVersionedRefStructure }
     * 
     */
    public StopAreaVersionedRefStructure createStopAreaVersionedRefStructure() {
        return new StopAreaVersionedRefStructure();
    }

    /**
     * Create an instance of {@link StopPointRefStructure }
     * 
     */
    public StopPointRefStructure createStopPointRefStructure() {
        return new StopPointRefStructure();
    }

    /**
     * Create an instance of {@link OpenDateRangeStructure }
     * 
     */
    public OpenDateRangeStructure createOpenDateRangeStructure() {
        return new OpenDateRangeStructure();
    }

    /**
     * Create an instance of {@link AnnotatedFerryRefStructure }
     * 
     */
    public AnnotatedFerryRefStructure createAnnotatedFerryRefStructure() {
        return new AnnotatedFerryRefStructure();
    }

    /**
     * Create an instance of {@link NaturalLanguageStringStructure }
     * 
     */
    public NaturalLanguageStringStructure createNaturalLanguageStringStructure() {
        return new NaturalLanguageStringStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.AlternativeDescriptors.Descriptor }
     * 
     */
    public StopPointStructure.AlternativeDescriptors.Descriptor createStopPointStructureAlternativeDescriptorsDescriptor() {
        return new StopPointStructure.AlternativeDescriptors.Descriptor();
    }

    /**
     * Create an instance of {@link StopPointVersionedRefStructure }
     * 
     */
    public StopPointVersionedRefStructure createStopPointVersionedRefStructure() {
        return new StopPointVersionedRefStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach.VariableBay }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach.VariableBay createStopClassificationStructureOffStreetBusAndCoachVariableBay() {
        return new StopClassificationStructure.OffStreet.BusAndCoach.VariableBay();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Ferry }
     * 
     */
    public StopClassificationStructure.OffStreet.Ferry createStopClassificationStructureOffStreetFerry() {
        return new StopClassificationStructure.OffStreet.Ferry();
    }

    /**
     * Create an instance of {@link MapSystemReferenceStructure }
     * 
     */
    public MapSystemReferenceStructure createMapSystemReferenceStructure() {
        return new MapSystemReferenceStructure();
    }

    /**
     * Create an instance of {@link StopAreasStructure }
     * 
     */
    public StopAreasStructure createStopAreasStructure() {
        return new StopAreasStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure }
     * 
     */
    public StopPointStructure createStopPointStructure() {
        return new StopPointStructure();
    }

    /**
     * Create an instance of {@link StopAreaRefsStructure }
     * 
     */
    public StopAreaRefsStructure createStopAreaRefsStructure() {
        return new StopAreaRefsStructure();
    }

    /**
     * Create an instance of {@link RegionVersionedRefStructure }
     * 
     */
    public RegionVersionedRefStructure createRegionVersionedRefStructure() {
        return new RegionVersionedRefStructure();
    }

    /**
     * Create an instance of {@link GridPositionStructure }
     * 
     */
    public GridPositionStructure createGridPositionStructure() {
        return new GridPositionStructure();
    }

    /**
     * Create an instance of {@link StopPointWrappedRefStructure }
     * 
     */
    public StopPointWrappedRefStructure createStopPointWrappedRefStructure() {
        return new StopPointWrappedRefStructure();
    }

    /**
     * Create an instance of {@link RegionRefStructure }
     * 
     */
    public RegionRefStructure createRegionRefStructure() {
        return new RegionRefStructure();
    }

    /**
     * Create an instance of {@link StopAreaRefStructure }
     * 
     */
    public StopAreaRefStructure createStopAreaRefStructure() {
        return new StopAreaRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedStopPointRefStructure }
     * 
     */
    public AnnotatedStopPointRefStructure createAnnotatedStopPointRefStructure() {
        return new AnnotatedStopPointRefStructure();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure.Season }
     * 
     */
    public DayAndTimeAvailabilityStructure.Season createDayAndTimeAvailabilityStructureSeason() {
        return new DayAndTimeAvailabilityStructure.Season();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Rail }
     * 
     */
    public StopClassificationStructure.OffStreet.Rail createStopClassificationStructureOffStreetRail() {
        return new StopClassificationStructure.OffStreet.Rail();
    }

    /**
     * Create an instance of {@link AnnotatedAirRefStructure }
     * 
     */
    public AnnotatedAirRefStructure createAnnotatedAirRefStructure() {
        return new AnnotatedAirRefStructure();
    }

    /**
     * Create an instance of {@link StopAreaWrappedRefStructure }
     * 
     */
    public StopAreaWrappedRefStructure createStopAreaWrappedRefStructure() {
        return new StopAreaWrappedRefStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Air }
     * 
     */
    public StopClassificationStructure.OffStreet.Air createStopClassificationStructureOffStreetAir() {
        return new StopClassificationStructure.OffStreet.Air();
    }

    /**
     * Create an instance of {@link AnnotatedMetroRefStructure }
     * 
     */
    public AnnotatedMetroRefStructure createAnnotatedMetroRefStructure() {
        return new AnnotatedMetroRefStructure();
    }

    /**
     * Create an instance of {@link DateCollectionStructure }
     * 
     */
    public DateCollectionStructure createDateCollectionStructure() {
        return new DateCollectionStructure();
    }

    /**
     * Create an instance of {@link PlusbusZoneRefStructure }
     * 
     */
    public PlusbusZoneRefStructure createPlusbusZoneRefStructure() {
        return new PlusbusZoneRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedRailRefStructure }
     * 
     */
    public AnnotatedRailRefStructure createAnnotatedRailRefStructure() {
        return new AnnotatedRailRefStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaRefsStructure }
     * 
     */
    public AdministrativeAreaRefsStructure createAdministrativeAreaRefsStructure() {
        return new AdministrativeAreaRefsStructure();
    }

    /**
     * Create an instance of {@link FullPersonNameStructure }
     * 
     */
    public FullPersonNameStructure createFullPersonNameStructure() {
        return new FullPersonNameStructure();
    }

    /**
     * Create an instance of {@link NptgLocalityRefStructure }
     * 
     */
    public NptgLocalityRefStructure createNptgLocalityRefStructure() {
        return new NptgLocalityRefStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaRefStructure }
     * 
     */
    public AdministrativeAreaRefStructure createAdministrativeAreaRefStructure() {
        return new AdministrativeAreaRefStructure();
    }

    /**
     * Create an instance of {@link NaturalLanguagePlaceNameStructure }
     * 
     */
    public NaturalLanguagePlaceNameStructure createNaturalLanguagePlaceNameStructure() {
        return new NaturalLanguagePlaceNameStructure();
    }

    /**
     * Create an instance of {@link DescriptorStructure }
     * 
     */
    public DescriptorStructure createDescriptorStructure() {
        return new DescriptorStructure();
    }

    /**
     * Create an instance of {@link NaPTAN }
     * 
     */
    public NaPTAN createNaPTAN() {
        return new NaPTAN();
    }

    /**
     * Create an instance of {@link HalfOpenDateTimeRangeStructure }
     * 
     */
    public HalfOpenDateTimeRangeStructure createHalfOpenDateTimeRangeStructure() {
        return new HalfOpenDateTimeRangeStructure();
    }

    /**
     * Create an instance of {@link BankHolidaysStructure.OtherPublicHoliday }
     * 
     */
    public BankHolidaysStructure.OtherPublicHoliday createBankHolidaysStructureOtherPublicHoliday() {
        return new BankHolidaysStructure.OtherPublicHoliday();
    }

    /**
     * Create an instance of {@link ClosedTimeRangeStructure }
     * 
     */
    public ClosedTimeRangeStructure createClosedTimeRangeStructure() {
        return new ClosedTimeRangeStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.Place }
     * 
     */
    public StopPointStructure.Place createStopPointStructurePlace() {
        return new StopPointStructure.Place();
    }

    /**
     * Create an instance of {@link NptgLocalityRefsStructure }
     * 
     */
    public NptgLocalityRefsStructure createNptgLocalityRefsStructure() {
        return new NptgLocalityRefsStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationSystemEnumeration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.naptan.org.uk/", name = "LocationSystem", defaultValue = "Grid")
    public JAXBElement<LocationSystemEnumeration> createLocationSystem(LocationSystemEnumeration value) {
        return new JAXBElement<LocationSystemEnumeration>(_LocationSystem_QNAME, LocationSystemEnumeration.class, null, value);
    }

}
