//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A group or area of related stops.
 * 
 * <p>Java class for StopAreaStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopAreaStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopAreaCode" type="{http://www.naptan.org.uk/}StopAreaCodeType"/>
 *         &lt;element name="PrivateCode" type="{http://www.naptan.org.uk/}PrivateCodeType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure"/>
 *         &lt;element name="ParentStopAreaRef" type="{http://www.naptan.org.uk/}StopPointVersionedRefStructure" minOccurs="0"/>
 *         &lt;element name="AdministrativeAreaRef" type="{http://www.naptan.org.uk/}AdministrativeAreaRefStructure"/>
 *         &lt;element name="StopAreaType" type="{http://www.naptan.org.uk/}StopAreaTypeEnumeration"/>
 *         &lt;element name="Location" type="{http://www.naptan.org.uk/}LocationStructure"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.naptan.org.uk/}RequiredModificationDetailsGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopAreaStructure", propOrder = {
    "stopAreaCode",
    "privateCode",
    "name",
    "parentStopAreaRef",
    "administrativeAreaRef",
    "stopAreaType",
    "location"
})
public class StopAreaStructure {

    @XmlElement(name = "StopAreaCode", required = true)
    protected String stopAreaCode;
    @XmlElement(name = "PrivateCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String privateCode;
    @XmlElement(name = "Name", required = true)
    protected NaturalLanguagePlaceNameStructure name;
    @XmlElement(name = "ParentStopAreaRef")
    protected StopPointVersionedRefStructure parentStopAreaRef;
    @XmlElement(name = "AdministrativeAreaRef", required = true)
    protected AdministrativeAreaRefStructure administrativeAreaRef;
    @XmlElement(name = "StopAreaType", required = true)
    protected StopAreaTypeEnumeration stopAreaType;
    @XmlElement(name = "Location", required = true)
    protected LocationStructure location;
    @XmlAttribute(name = "CreationDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification")
    protected ModificationEnumeration modification;
    @XmlAttribute(name = "RevisionNumber")
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "Status")
    protected StatusEnumeration status;

    /**
     * Gets the value of the stopAreaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopAreaCode() {
        return stopAreaCode;
    }

    /**
     * Sets the value of the stopAreaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopAreaCode(String value) {
        this.stopAreaCode = value;
    }

    /**
     * Gets the value of the privateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateCode() {
        return privateCode;
    }

    /**
     * Sets the value of the privateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateCode(String value) {
        this.privateCode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setName(NaturalLanguagePlaceNameStructure value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentStopAreaRef property.
     * 
     * @return
     *     possible object is
     *     {@link StopPointVersionedRefStructure }
     *     
     */
    public StopPointVersionedRefStructure getParentStopAreaRef() {
        return parentStopAreaRef;
    }

    /**
     * Sets the value of the parentStopAreaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPointVersionedRefStructure }
     *     
     */
    public void setParentStopAreaRef(StopPointVersionedRefStructure value) {
        this.parentStopAreaRef = value;
    }

    /**
     * Gets the value of the administrativeAreaRef property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public AdministrativeAreaRefStructure getAdministrativeAreaRef() {
        return administrativeAreaRef;
    }

    /**
     * Sets the value of the administrativeAreaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public void setAdministrativeAreaRef(AdministrativeAreaRefStructure value) {
        this.administrativeAreaRef = value;
    }

    /**
     * Gets the value of the stopAreaType property.
     * 
     * @return
     *     possible object is
     *     {@link StopAreaTypeEnumeration }
     *     
     */
    public StopAreaTypeEnumeration getStopAreaType() {
        return stopAreaType;
    }

    /**
     * Sets the value of the stopAreaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopAreaTypeEnumeration }
     *     
     */
    public void setStopAreaType(StopAreaTypeEnumeration value) {
        this.stopAreaType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setLocation(LocationStructure value) {
        this.location = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the modificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    /**
     * Sets the value of the modificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationEnumeration }
     *     
     */
    public ModificationEnumeration getModification() {
        if (modification == null) {
            return ModificationEnumeration.NEW;
        } else {
            return modification;
        }
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationEnumeration }
     *     
     */
    public void setModification(ModificationEnumeration value) {
        this.modification = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnumeration }
     *     
     */
    public StatusEnumeration getStatus() {
        if (status == null) {
            return StatusEnumeration.ACTIVE;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnumeration }
     *     
     */
    public void setStatus(StatusEnumeration value) {
        this.status = value;
    }

}
