//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StopAreaTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StopAreaTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="GPBS"/>
 *     &lt;enumeration value="pairedOnStreetBusStops"/>
 *     &lt;enumeration value="GCLS"/>
 *     &lt;enumeration value="clusteredOnStreetBusStops"/>
 *     &lt;enumeration value="GAIR"/>
 *     &lt;enumeration value="airportBuilding"/>
 *     &lt;enumeration value="GBCS"/>
 *     &lt;enumeration value="busOrCoachStation"/>
 *     &lt;enumeration value="GFTD"/>
 *     &lt;enumeration value="ferryTerminalOrDockBuilding"/>
 *     &lt;enumeration value="GTMU"/>
 *     &lt;enumeration value="tramMetroOrUndergroundStation"/>
 *     &lt;enumeration value="GRLS"/>
 *     &lt;enumeration value="railwayStation"/>
 *     &lt;enumeration value="GMLT"/>
 *     &lt;enumeration value="multimodaInterchange"/>
 *     &lt;enumeration value="GOTH"/>
 *     &lt;enumeration value="otherStructure"/>
 *     &lt;enumeration value="GCCH"/>
 *     &lt;enumeration value="coachCoverage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StopAreaTypeEnumeration")
@XmlEnum
public enum StopAreaTypeEnumeration {


    /**
     * Paired on-street Bus / Coach / Tram stops.
     * 
     */
    GPBS("GPBS"),
    @XmlEnumValue("pairedOnStreetBusStops")
    PAIRED_ON_STREET_BUS_STOPS("pairedOnStreetBusStops"),

    /**
     * Clustered on-street Bus / Coach / Tram stops.
     * 
     */
    GCLS("GCLS"),
    @XmlEnumValue("clusteredOnStreetBusStops")
    CLUSTERED_ON_STREET_BUS_STOPS("clusteredOnStreetBusStops"),

    /**
     * Airport Building.
     * 
     */
    GAIR("GAIR"),
    @XmlEnumValue("airportBuilding")
    AIRPORT_BUILDING("airportBuilding"),

    /**
     * Bus / Coach Station.
     * 
     */
    GBCS("GBCS"),
    @XmlEnumValue("busOrCoachStation")
    BUS_OR_COACH_STATION("busOrCoachStation"),

    /**
     * Ferry Terminal / Dock Building.
     * 
     */
    GFTD("GFTD"),
    @XmlEnumValue("ferryTerminalOrDockBuilding")
    FERRY_TERMINAL_OR_DOCK_BUILDING("ferryTerminalOrDockBuilding"),

    /**
     * Tram / Metro / Underground Station.
     * 
     */
    GTMU("GTMU"),
    @XmlEnumValue("tramMetroOrUndergroundStation")
    TRAM_METRO_OR_UNDERGROUND_STATION("tramMetroOrUndergroundStation"),

    /**
     * Railway station.
     * 
     */
    GRLS("GRLS"),
    @XmlEnumValue("railwayStation")
    RAILWAY_STATION("railwayStation"),

    /**
     * Multimode Interchange.
     * 
     */
    GMLT("GMLT"),
    @XmlEnumValue("multimodaInterchange")
    MULTIMODA_INTERCHANGE("multimodaInterchange"),

    /**
     * Other Structure.
     * 
     */
    GOTH("GOTH"),
    @XmlEnumValue("otherStructure")
    OTHER_STRUCTURE("otherStructure"),

    /**
     * Coach Service Coverage.
     * 
     */
    GCCH("GCCH"),
    @XmlEnumValue("coachCoverage")
    COACH_COVERAGE("coachCoverage");
    private final String value;

    StopAreaTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StopAreaTypeEnumeration fromValue(String v) {
        for (StopAreaTypeEnumeration c: StopAreaTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
