//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StopTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StopTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="AIR"/>
 *     &lt;enumeration value="airportEntrance"/>
 *     &lt;enumeration value="GAT"/>
 *     &lt;enumeration value="airAccessArea"/>
 *     &lt;enumeration value="FTD"/>
 *     &lt;enumeration value="ferryTerminalDockEntrance"/>
 *     &lt;enumeration value="FER"/>
 *     &lt;enumeration value="ferryDockAccessArea"/>
 *     &lt;enumeration value="FBT"/>
 *     &lt;enumeration value="FerryBerth"/>
 *     &lt;enumeration value="RSE"/>
 *     &lt;enumeration value="railStationEntrance"/>
 *     &lt;enumeration value="RLY"/>
 *     &lt;enumeration value="railAccessArea"/>
 *     &lt;enumeration value="RPL"/>
 *     &lt;enumeration value="railPlatform"/>
 *     &lt;enumeration value="TMU"/>
 *     &lt;enumeration value="tramMetroUndergroundStationEntrance"/>
 *     &lt;enumeration value="MET"/>
 *     &lt;enumeration value="tramMetroUndergroundAccessArea"/>
 *     &lt;enumeration value="PLT"/>
 *     &lt;enumeration value="tramMetroUndergroundPlatform"/>
 *     &lt;enumeration value="BCE"/>
 *     &lt;enumeration value="busCoachTramStationEntrance"/>
 *     &lt;enumeration value="BST"/>
 *     &lt;enumeration value="busCoachStationAccessArea"/>
 *     &lt;enumeration value="BCS"/>
 *     &lt;enumeration value="busCoachTramStationBay"/>
 *     &lt;enumeration value="BCQ"/>
 *     &lt;enumeration value="busCoachTramStationVariableBay"/>
 *     &lt;enumeration value="BCT"/>
 *     &lt;enumeration value="busCoachTramOnStreetPoint"/>
 *     &lt;enumeration value="TXR"/>
 *     &lt;enumeration value="taxiRank"/>
 *     &lt;enumeration value="STR"/>
 *     &lt;enumeration value="sharedTaxiRank"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StopTypeEnumeration")
@XmlEnum
public enum StopTypeEnumeration {


    /**
     * Airport Entrance.
     * 
     */
    AIR("AIR"),
    @XmlEnumValue("airportEntrance")
    AIRPORT_ENTRANCE("airportEntrance"),

    /**
     * Air Airside Area.
     * 
     */
    GAT("GAT"),
    @XmlEnumValue("airAccessArea")
    AIR_ACCESS_AREA("airAccessArea"),

    /**
     * Ferry Terminal / Dock Entrance.
     * 
     */
    FTD("FTD"),
    @XmlEnumValue("ferryTerminalDockEntrance")
    FERRY_TERMINAL_DOCK_ENTRANCE("ferryTerminalDockEntrance"),

    /**
     * Ferry / Dock Berth Area.
     * 
     */
    FER("FER"),
    @XmlEnumValue("ferryDockAccessArea")
    FERRY_DOCK_ACCESS_AREA("ferryDockAccessArea"),
    FBT("FBT"),
    @XmlEnumValue("FerryBerth")
    FERRY_BERTH("FerryBerth"),

    /**
     * Rail Station Entrance.
     * 
     */
    RSE("RSE"),
    @XmlEnumValue("railStationEntrance")
    RAIL_STATION_ENTRANCE("railStationEntrance"),

    /**
     * Rail Platform Access Area.
     * 
     */
    RLY("RLY"),
    @XmlEnumValue("railAccessArea")
    RAIL_ACCESS_AREA("railAccessArea"),
    RPL("RPL"),
    @XmlEnumValue("railPlatform")
    RAIL_PLATFORM("railPlatform"),

    /**
     * Tram / Metro / Underground Entrance.
     * 
     */
    TMU("TMU"),
    @XmlEnumValue("tramMetroUndergroundStationEntrance")
    TRAM_METRO_UNDERGROUND_STATION_ENTRANCE("tramMetroUndergroundStationEntrance"),
    MET("MET"),
    @XmlEnumValue("tramMetroUndergroundAccessArea")
    TRAM_METRO_UNDERGROUND_ACCESS_AREA("tramMetroUndergroundAccessArea"),

    /**
     * Metro and Underground   Platform Access Area.
     * 
     */
    PLT("PLT"),
    @XmlEnumValue("tramMetroUndergroundPlatform")
    TRAM_METRO_UNDERGROUND_PLATFORM("tramMetroUndergroundPlatform"),

    /**
     * Bus / Coach Station Entrance.
     * 
     */
    BCE("BCE"),
    @XmlEnumValue("busCoachTramStationEntrance")
    BUS_COACH_TRAM_STATION_ENTRANCE("busCoachTramStationEntrance"),
    BST("BST"),
    @XmlEnumValue("busCoachStationAccessArea")
    BUS_COACH_STATION_ACCESS_AREA("busCoachStationAccessArea"),

    /**
     * Bus / Coach bay / stand / stance within Bus / Coach Stations.
     * 
     */
    BCS("BCS"),
    @XmlEnumValue("busCoachTramStationBay")
    BUS_COACH_TRAM_STATION_BAY("busCoachTramStationBay"),
    BCQ("BCQ"),
    @XmlEnumValue("busCoachTramStationVariableBay")
    BUS_COACH_TRAM_STATION_VARIABLE_BAY("busCoachTramStationVariableBay"),

    /**
     * On street Bus / Coach / Tram Stop.
     * 
     */
    BCT("BCT"),
    @XmlEnumValue("busCoachTramOnStreetPoint")
    BUS_COACH_TRAM_ON_STREET_POINT("busCoachTramOnStreetPoint"),

    /**
     * Taxi Rank (head of).
     * 
     */
    TXR("TXR"),
    @XmlEnumValue("taxiRank")
    TAXI_RANK("taxiRank"),

    /**
     * Shared Taxi Rank (head of).
     * 
     */
    STR("STR"),
    @XmlEnumValue("sharedTaxiRank")
    SHARED_TAXI_RANK("sharedTaxiRank");
    private final String value;

    StopTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StopTypeEnumeration fromValue(String v) {
        for (StopTypeEnumeration c: StopTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
