//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * Data type for Type of stop. Some stop types have required subelements.
 * 
 * <p>Java class for StopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopType" type="{http://www.naptan.org.uk/}StopTypeEnumeration"/>
 *         &lt;choice>
 *           &lt;element name="OnStreet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="Bus">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="BusStopType" type="{http://www.naptan.org.uk/}BusStopTypeEnumeration"/>
 *                               &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration"/>
 *                               &lt;group ref="{http://www.naptan.org.uk/}BusStopClassificationGroup"/>
 *                               &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Taxi">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="OffStreet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="Air">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;/choice>
 *                               &lt;element name="AnnotatedAirRef" type="{http://www.naptan.org.uk/}AnnotatedAirRefStructure" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Ferry">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="Berth" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;/choice>
 *                               &lt;element name="AnnotatedFerryRef" type="{http://www.naptan.org.uk/}AnnotatedFerryRefStructure" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Rail">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;/choice>
 *                               &lt;element name="AnnotatedRailRef" type="{http://www.naptan.org.uk/}AnnotatedRailRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Metro">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;/choice>
 *                               &lt;element name="AnnotatedMetroRef" type="{http://www.naptan.org.uk/}AnnotatedMetroRefStructure" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BusAndCoach">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                                 &lt;element name="Bay">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="VariableBay">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/choice>
 *                               &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopClassificationStructure", propOrder = {
    "stopType",
    "onStreet",
    "offStreet"
})
public class StopClassificationStructure {

    @XmlElement(name = "StopType", required = true)
    protected StopTypeEnumeration stopType;
    @XmlElement(name = "OnStreet")
    protected StopClassificationStructure.OnStreet onStreet;
    @XmlElement(name = "OffStreet")
    protected StopClassificationStructure.OffStreet offStreet;

    /**
     * Gets the value of the stopType property.
     * 
     * @return
     *     possible object is
     *     {@link StopTypeEnumeration }
     *     
     */
    public StopTypeEnumeration getStopType() {
        return stopType;
    }

    /**
     * Sets the value of the stopType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopTypeEnumeration }
     *     
     */
    public void setStopType(StopTypeEnumeration value) {
        this.stopType = value;
    }

    /**
     * Gets the value of the onStreet property.
     * 
     * @return
     *     possible object is
     *     {@link StopClassificationStructure.OnStreet }
     *     
     */
    public StopClassificationStructure.OnStreet getOnStreet() {
        return onStreet;
    }

    /**
     * Sets the value of the onStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopClassificationStructure.OnStreet }
     *     
     */
    public void setOnStreet(StopClassificationStructure.OnStreet value) {
        this.onStreet = value;
    }

    /**
     * Gets the value of the offStreet property.
     * 
     * @return
     *     possible object is
     *     {@link StopClassificationStructure.OffStreet }
     *     
     */
    public StopClassificationStructure.OffStreet getOffStreet() {
        return offStreet;
    }

    /**
     * Sets the value of the offStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopClassificationStructure.OffStreet }
     *     
     */
    public void setOffStreet(StopClassificationStructure.OffStreet value) {
        this.offStreet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Air">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;/choice>
     *                   &lt;element name="AnnotatedAirRef" type="{http://www.naptan.org.uk/}AnnotatedAirRefStructure" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Ferry">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="Berth" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;/choice>
     *                   &lt;element name="AnnotatedFerryRef" type="{http://www.naptan.org.uk/}AnnotatedFerryRefStructure" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Rail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;/choice>
     *                   &lt;element name="AnnotatedRailRef" type="{http://www.naptan.org.uk/}AnnotatedRailRefStructure" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Metro">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;/choice>
     *                   &lt;element name="AnnotatedMetroRef" type="{http://www.naptan.org.uk/}AnnotatedMetroRefStructure" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BusAndCoach">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                     &lt;element name="Bay">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="VariableBay">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                   &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "air",
        "ferry",
        "rail",
        "metro",
        "busAndCoach"
    })
    public static class OffStreet {

        @XmlElement(name = "Air")
        protected StopClassificationStructure.OffStreet.Air air;
        @XmlElement(name = "Ferry")
        protected StopClassificationStructure.OffStreet.Ferry ferry;
        @XmlElement(name = "Rail")
        protected StopClassificationStructure.OffStreet.Rail rail;
        @XmlElement(name = "Metro")
        protected StopClassificationStructure.OffStreet.Metro metro;
        @XmlElement(name = "BusAndCoach")
        protected StopClassificationStructure.OffStreet.BusAndCoach busAndCoach;

        /**
         * Gets the value of the air property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OffStreet.Air }
         *     
         */
        public StopClassificationStructure.OffStreet.Air getAir() {
            return air;
        }

        /**
         * Sets the value of the air property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OffStreet.Air }
         *     
         */
        public void setAir(StopClassificationStructure.OffStreet.Air value) {
            this.air = value;
        }

        /**
         * Gets the value of the ferry property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OffStreet.Ferry }
         *     
         */
        public StopClassificationStructure.OffStreet.Ferry getFerry() {
            return ferry;
        }

        /**
         * Sets the value of the ferry property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OffStreet.Ferry }
         *     
         */
        public void setFerry(StopClassificationStructure.OffStreet.Ferry value) {
            this.ferry = value;
        }

        /**
         * Gets the value of the rail property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OffStreet.Rail }
         *     
         */
        public StopClassificationStructure.OffStreet.Rail getRail() {
            return rail;
        }

        /**
         * Sets the value of the rail property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OffStreet.Rail }
         *     
         */
        public void setRail(StopClassificationStructure.OffStreet.Rail value) {
            this.rail = value;
        }

        /**
         * Gets the value of the metro property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OffStreet.Metro }
         *     
         */
        public StopClassificationStructure.OffStreet.Metro getMetro() {
            return metro;
        }

        /**
         * Sets the value of the metro property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OffStreet.Metro }
         *     
         */
        public void setMetro(StopClassificationStructure.OffStreet.Metro value) {
            this.metro = value;
        }

        /**
         * Gets the value of the busAndCoach property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OffStreet.BusAndCoach }
         *     
         */
        public StopClassificationStructure.OffStreet.BusAndCoach getBusAndCoach() {
            return busAndCoach;
        }

        /**
         * Sets the value of the busAndCoach property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OffStreet.BusAndCoach }
         *     
         */
        public void setBusAndCoach(StopClassificationStructure.OffStreet.BusAndCoach value) {
            this.busAndCoach = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;/choice>
         *         &lt;element name="AnnotatedAirRef" type="{http://www.naptan.org.uk/}AnnotatedAirRefStructure" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entrance",
            "accessArea",
            "annotatedAirRef"
        })
        public static class Air {

            @XmlElement(name = "Entrance")
            protected String entrance;
            @XmlElement(name = "AccessArea")
            protected String accessArea;
            @XmlElement(name = "AnnotatedAirRef")
            protected AnnotatedAirRefStructure annotatedAirRef;

            /**
             * Gets the value of the entrance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntrance() {
                return entrance;
            }

            /**
             * Sets the value of the entrance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntrance(String value) {
                this.entrance = value;
            }

            /**
             * Gets the value of the accessArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessArea() {
                return accessArea;
            }

            /**
             * Sets the value of the accessArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessArea(String value) {
                this.accessArea = value;
            }

            /**
             * Gets the value of the annotatedAirRef property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotatedAirRefStructure }
             *     
             */
            public AnnotatedAirRefStructure getAnnotatedAirRef() {
                return annotatedAirRef;
            }

            /**
             * Sets the value of the annotatedAirRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotatedAirRefStructure }
             *     
             */
            public void setAnnotatedAirRef(AnnotatedAirRefStructure value) {
                this.annotatedAirRef = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="Bay">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="VariableBay">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *         &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entrance",
            "accessArea",
            "bay",
            "variableBay",
            "annotatedCoachRef"
        })
        public static class BusAndCoach {

            @XmlElement(name = "Entrance")
            protected String entrance;
            @XmlElement(name = "AccessArea")
            protected String accessArea;
            @XmlElement(name = "Bay")
            protected StopClassificationStructure.OffStreet.BusAndCoach.Bay bay;
            @XmlElement(name = "VariableBay")
            protected StopClassificationStructure.OffStreet.BusAndCoach.VariableBay variableBay;
            @XmlElement(name = "AnnotatedCoachRef")
            protected List<AnnotatedCoachRefStructure> annotatedCoachRef;

            /**
             * Gets the value of the entrance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntrance() {
                return entrance;
            }

            /**
             * Sets the value of the entrance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntrance(String value) {
                this.entrance = value;
            }

            /**
             * Gets the value of the accessArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessArea() {
                return accessArea;
            }

            /**
             * Sets the value of the accessArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessArea(String value) {
                this.accessArea = value;
            }

            /**
             * Gets the value of the bay property.
             * 
             * @return
             *     possible object is
             *     {@link StopClassificationStructure.OffStreet.BusAndCoach.Bay }
             *     
             */
            public StopClassificationStructure.OffStreet.BusAndCoach.Bay getBay() {
                return bay;
            }

            /**
             * Sets the value of the bay property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopClassificationStructure.OffStreet.BusAndCoach.Bay }
             *     
             */
            public void setBay(StopClassificationStructure.OffStreet.BusAndCoach.Bay value) {
                this.bay = value;
            }

            /**
             * Gets the value of the variableBay property.
             * 
             * @return
             *     possible object is
             *     {@link StopClassificationStructure.OffStreet.BusAndCoach.VariableBay }
             *     
             */
            public StopClassificationStructure.OffStreet.BusAndCoach.VariableBay getVariableBay() {
                return variableBay;
            }

            /**
             * Sets the value of the variableBay property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopClassificationStructure.OffStreet.BusAndCoach.VariableBay }
             *     
             */
            public void setVariableBay(StopClassificationStructure.OffStreet.BusAndCoach.VariableBay value) {
                this.variableBay = value;
            }

            /**
             * Gets the value of the annotatedCoachRef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the annotatedCoachRef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAnnotatedCoachRef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnnotatedCoachRefStructure }
             * 
             * 
             */
            public List<AnnotatedCoachRefStructure> getAnnotatedCoachRef() {
                if (annotatedCoachRef == null) {
                    annotatedCoachRef = new ArrayList<AnnotatedCoachRefStructure>();
                }
                return this.annotatedCoachRef;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "timingStatus"
            })
            public static class Bay {

                @XmlElement(name = "TimingStatus")
                protected TimingStatusEnumeration timingStatus;

                /**
                 * Gets the value of the timingStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TimingStatusEnumeration }
                 *     
                 */
                public TimingStatusEnumeration getTimingStatus() {
                    return timingStatus;
                }

                /**
                 * Sets the value of the timingStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TimingStatusEnumeration }
                 *     
                 */
                public void setTimingStatus(TimingStatusEnumeration value) {
                    this.timingStatus = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "timingStatus"
            })
            public static class VariableBay {

                @XmlElement(name = "TimingStatus")
                protected TimingStatusEnumeration timingStatus;

                /**
                 * Gets the value of the timingStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TimingStatusEnumeration }
                 *     
                 */
                public TimingStatusEnumeration getTimingStatus() {
                    return timingStatus;
                }

                /**
                 * Sets the value of the timingStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TimingStatusEnumeration }
                 *     
                 */
                public void setTimingStatus(TimingStatusEnumeration value) {
                    this.timingStatus = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="Berth" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;/choice>
         *         &lt;element name="AnnotatedFerryRef" type="{http://www.naptan.org.uk/}AnnotatedFerryRefStructure" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entrance",
            "accessArea",
            "berth",
            "annotatedFerryRef"
        })
        public static class Ferry {

            @XmlElement(name = "Entrance")
            protected String entrance;
            @XmlElement(name = "AccessArea")
            protected String accessArea;
            @XmlElement(name = "Berth")
            protected String berth;
            @XmlElement(name = "AnnotatedFerryRef")
            protected AnnotatedFerryRefStructure annotatedFerryRef;

            /**
             * Gets the value of the entrance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntrance() {
                return entrance;
            }

            /**
             * Sets the value of the entrance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntrance(String value) {
                this.entrance = value;
            }

            /**
             * Gets the value of the accessArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessArea() {
                return accessArea;
            }

            /**
             * Sets the value of the accessArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessArea(String value) {
                this.accessArea = value;
            }

            /**
             * Gets the value of the berth property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBerth() {
                return berth;
            }

            /**
             * Sets the value of the berth property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBerth(String value) {
                this.berth = value;
            }

            /**
             * Gets the value of the annotatedFerryRef property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotatedFerryRefStructure }
             *     
             */
            public AnnotatedFerryRefStructure getAnnotatedFerryRef() {
                return annotatedFerryRef;
            }

            /**
             * Sets the value of the annotatedFerryRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotatedFerryRefStructure }
             *     
             */
            public void setAnnotatedFerryRef(AnnotatedFerryRefStructure value) {
                this.annotatedFerryRef = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;/choice>
         *         &lt;element name="AnnotatedMetroRef" type="{http://www.naptan.org.uk/}AnnotatedMetroRefStructure" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entrance",
            "accessArea",
            "platform",
            "annotatedMetroRef"
        })
        public static class Metro {

            @XmlElement(name = "Entrance")
            protected String entrance;
            @XmlElement(name = "AccessArea")
            protected String accessArea;
            @XmlElement(name = "Platform")
            protected String platform;
            @XmlElement(name = "AnnotatedMetroRef")
            protected AnnotatedMetroRefStructure annotatedMetroRef;

            /**
             * Gets the value of the entrance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntrance() {
                return entrance;
            }

            /**
             * Sets the value of the entrance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntrance(String value) {
                this.entrance = value;
            }

            /**
             * Gets the value of the accessArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessArea() {
                return accessArea;
            }

            /**
             * Sets the value of the accessArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessArea(String value) {
                this.accessArea = value;
            }

            /**
             * Gets the value of the platform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlatform() {
                return platform;
            }

            /**
             * Sets the value of the platform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlatform(String value) {
                this.platform = value;
            }

            /**
             * Gets the value of the annotatedMetroRef property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotatedMetroRefStructure }
             *     
             */
            public AnnotatedMetroRefStructure getAnnotatedMetroRef() {
                return annotatedMetroRef;
            }

            /**
             * Sets the value of the annotatedMetroRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotatedMetroRefStructure }
             *     
             */
            public void setAnnotatedMetroRef(AnnotatedMetroRefStructure value) {
                this.annotatedMetroRef = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
         *           &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;/choice>
         *         &lt;element name="AnnotatedRailRef" type="{http://www.naptan.org.uk/}AnnotatedRailRefStructure" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entrance",
            "accessArea",
            "platform",
            "annotatedRailRef"
        })
        public static class Rail {

            @XmlElement(name = "Entrance")
            protected String entrance;
            @XmlElement(name = "AccessArea")
            protected String accessArea;
            @XmlElement(name = "Platform")
            protected String platform;
            @XmlElement(name = "AnnotatedRailRef")
            protected List<AnnotatedRailRefStructure> annotatedRailRef;

            /**
             * Gets the value of the entrance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntrance() {
                return entrance;
            }

            /**
             * Sets the value of the entrance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntrance(String value) {
                this.entrance = value;
            }

            /**
             * Gets the value of the accessArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessArea() {
                return accessArea;
            }

            /**
             * Sets the value of the accessArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessArea(String value) {
                this.accessArea = value;
            }

            /**
             * Gets the value of the platform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlatform() {
                return platform;
            }

            /**
             * Sets the value of the platform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlatform(String value) {
                this.platform = value;
            }

            /**
             * Gets the value of the annotatedRailRef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the annotatedRailRef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAnnotatedRailRef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnnotatedRailRefStructure }
             * 
             * 
             */
            public List<AnnotatedRailRefStructure> getAnnotatedRailRef() {
                if (annotatedRailRef == null) {
                    annotatedRailRef = new ArrayList<AnnotatedRailRefStructure>();
                }
                return this.annotatedRailRef;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Bus">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BusStopType" type="{http://www.naptan.org.uk/}BusStopTypeEnumeration"/>
     *                   &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration"/>
     *                   &lt;group ref="{http://www.naptan.org.uk/}BusStopClassificationGroup"/>
     *                   &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Taxi">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bus",
        "taxi"
    })
    public static class OnStreet {

        @XmlElement(name = "Bus")
        protected StopClassificationStructure.OnStreet.Bus bus;
        @XmlElement(name = "Taxi")
        protected StopClassificationStructure.OnStreet.Taxi taxi;

        /**
         * Gets the value of the bus property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OnStreet.Bus }
         *     
         */
        public StopClassificationStructure.OnStreet.Bus getBus() {
            return bus;
        }

        /**
         * Sets the value of the bus property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OnStreet.Bus }
         *     
         */
        public void setBus(StopClassificationStructure.OnStreet.Bus value) {
            this.bus = value;
        }

        /**
         * Gets the value of the taxi property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OnStreet.Taxi }
         *     
         */
        public StopClassificationStructure.OnStreet.Taxi getTaxi() {
            return taxi;
        }

        /**
         * Sets the value of the taxi property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OnStreet.Taxi }
         *     
         */
        public void setTaxi(StopClassificationStructure.OnStreet.Taxi value) {
            this.taxi = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BusStopType" type="{http://www.naptan.org.uk/}BusStopTypeEnumeration"/>
         *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration"/>
         *         &lt;group ref="{http://www.naptan.org.uk/}BusStopClassificationGroup"/>
         *         &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "busStopType",
            "timingStatus",
            "markedPoint",
            "unmarkedPoint",
            "hailAndRideSection",
            "flexibleZone",
            "annotatedCoachRef"
        })
        public static class Bus {

            @XmlElement(name = "BusStopType", required = true)
            protected BusStopTypeEnumeration busStopType;
            @XmlElement(name = "TimingStatus", required = true)
            protected TimingStatusEnumeration timingStatus;
            @XmlElement(name = "MarkedPoint")
            protected StopClassificationStructure.OnStreet.Bus.MarkedPoint markedPoint;
            @XmlElement(name = "UnmarkedPoint")
            protected StopClassificationStructure.OnStreet.Bus.UnmarkedPoint unmarkedPoint;
            @XmlElement(name = "HailAndRideSection")
            protected HailAndRideSectionStructure hailAndRideSection;
            @XmlElement(name = "FlexibleZone")
            protected FlexibleZoneStructure flexibleZone;
            @XmlElement(name = "AnnotatedCoachRef")
            protected List<AnnotatedCoachRefStructure> annotatedCoachRef;

            /**
             * Gets the value of the busStopType property.
             * 
             * @return
             *     possible object is
             *     {@link BusStopTypeEnumeration }
             *     
             */
            public BusStopTypeEnumeration getBusStopType() {
                return busStopType;
            }

            /**
             * Sets the value of the busStopType property.
             * 
             * @param value
             *     allowed object is
             *     {@link BusStopTypeEnumeration }
             *     
             */
            public void setBusStopType(BusStopTypeEnumeration value) {
                this.busStopType = value;
            }

            /**
             * Gets the value of the timingStatus property.
             * 
             * @return
             *     possible object is
             *     {@link TimingStatusEnumeration }
             *     
             */
            public TimingStatusEnumeration getTimingStatus() {
                return timingStatus;
            }

            /**
             * Sets the value of the timingStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link TimingStatusEnumeration }
             *     
             */
            public void setTimingStatus(TimingStatusEnumeration value) {
                this.timingStatus = value;
            }

            /**
             * Gets the value of the markedPoint property.
             * 
             * @return
             *     possible object is
             *     {@link StopClassificationStructure.OnStreet.Bus.MarkedPoint }
             *     
             */
            public StopClassificationStructure.OnStreet.Bus.MarkedPoint getMarkedPoint() {
                return markedPoint;
            }

            /**
             * Sets the value of the markedPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopClassificationStructure.OnStreet.Bus.MarkedPoint }
             *     
             */
            public void setMarkedPoint(StopClassificationStructure.OnStreet.Bus.MarkedPoint value) {
                this.markedPoint = value;
            }

            /**
             * Gets the value of the unmarkedPoint property.
             * 
             * @return
             *     possible object is
             *     {@link StopClassificationStructure.OnStreet.Bus.UnmarkedPoint }
             *     
             */
            public StopClassificationStructure.OnStreet.Bus.UnmarkedPoint getUnmarkedPoint() {
                return unmarkedPoint;
            }

            /**
             * Sets the value of the unmarkedPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopClassificationStructure.OnStreet.Bus.UnmarkedPoint }
             *     
             */
            public void setUnmarkedPoint(StopClassificationStructure.OnStreet.Bus.UnmarkedPoint value) {
                this.unmarkedPoint = value;
            }

            /**
             * Gets the value of the hailAndRideSection property.
             * 
             * @return
             *     possible object is
             *     {@link HailAndRideSectionStructure }
             *     
             */
            public HailAndRideSectionStructure getHailAndRideSection() {
                return hailAndRideSection;
            }

            /**
             * Sets the value of the hailAndRideSection property.
             * 
             * @param value
             *     allowed object is
             *     {@link HailAndRideSectionStructure }
             *     
             */
            public void setHailAndRideSection(HailAndRideSectionStructure value) {
                this.hailAndRideSection = value;
            }

            /**
             * Gets the value of the flexibleZone property.
             * 
             * @return
             *     possible object is
             *     {@link FlexibleZoneStructure }
             *     
             */
            public FlexibleZoneStructure getFlexibleZone() {
                return flexibleZone;
            }

            /**
             * Sets the value of the flexibleZone property.
             * 
             * @param value
             *     allowed object is
             *     {@link FlexibleZoneStructure }
             *     
             */
            public void setFlexibleZone(FlexibleZoneStructure value) {
                this.flexibleZone = value;
            }

            /**
             * Gets the value of the annotatedCoachRef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the annotatedCoachRef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAnnotatedCoachRef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnnotatedCoachRefStructure }
             * 
             * 
             */
            public List<AnnotatedCoachRefStructure> getAnnotatedCoachRef() {
                if (annotatedCoachRef == null) {
                    annotatedCoachRef = new ArrayList<AnnotatedCoachRefStructure>();
                }
                return this.annotatedCoachRef;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DefaultWaitTime" type="{http://www.naptan.org.uk/}DurationType" minOccurs="0"/>
             *         &lt;element name="Bearing" type="{http://www.naptan.org.uk/}BearingStructure"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "defaultWaitTime",
                "bearing"
            })
            public static class MarkedPoint {

                @XmlElement(name = "DefaultWaitTime")
                protected Duration defaultWaitTime;
                @XmlElement(name = "Bearing", required = true)
                protected BearingStructure bearing;

                /**
                 * Gets the value of the defaultWaitTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Duration }
                 *     
                 */
                public Duration getDefaultWaitTime() {
                    return defaultWaitTime;
                }

                /**
                 * Sets the value of the defaultWaitTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Duration }
                 *     
                 */
                public void setDefaultWaitTime(Duration value) {
                    this.defaultWaitTime = value;
                }

                /**
                 * Gets the value of the bearing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BearingStructure }
                 *     
                 */
                public BearingStructure getBearing() {
                    return bearing;
                }

                /**
                 * Sets the value of the bearing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BearingStructure }
                 *     
                 */
                public void setBearing(BearingStructure value) {
                    this.bearing = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Bearing" type="{http://www.naptan.org.uk/}BearingStructure"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bearing"
            })
            public static class UnmarkedPoint {

                @XmlElement(name = "Bearing", required = true)
                protected BearingStructure bearing;

                /**
                 * Gets the value of the bearing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BearingStructure }
                 *     
                 */
                public BearingStructure getBearing() {
                    return bearing;
                }

                /**
                 * Sets the value of the bearing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BearingStructure }
                 *     
                 */
                public void setBearing(BearingStructure value) {
                    this.bearing = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxiRank",
            "sharedTaxiRank"
        })
        public static class Taxi {

            @XmlElement(name = "TaxiRank")
            protected String taxiRank;
            @XmlElement(name = "SharedTaxiRank")
            protected String sharedTaxiRank;

            /**
             * Gets the value of the taxiRank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxiRank() {
                return taxiRank;
            }

            /**
             * Sets the value of the taxiRank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxiRank(String value) {
                this.taxiRank = value;
            }

            /**
             * Gets the value of the sharedTaxiRank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSharedTaxiRank() {
                return sharedTaxiRank;
            }

            /**
             * Sets the value of the sharedTaxiRank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSharedTaxiRank(String value) {
                this.sharedTaxiRank = value;
            }

        }

    }

}
