//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A local NaPTAN stop definition.
 * 
 * <p>Java class for StopPointStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopPointStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AtcoCode" type="{http://www.naptan.org.uk/}AtcoCodeType"/>
 *         &lt;group ref="{http://www.naptan.org.uk/}StopIdentifierGroup"/>
 *         &lt;element name="Descriptor" type="{http://www.naptan.org.uk/}DescriptorStructure"/>
 *         &lt;element name="AlternativeDescriptors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Descriptor" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.naptan.org.uk/}DescriptorStructure">
 *                           &lt;attGroup ref="{http://www.naptan.org.uk/}RequiredModificationDetailsGroup"/>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Place">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NptgLocalityRef" type="{http://www.naptan.org.uk/}NptgLocalityRefStructure"/>
 *                   &lt;element name="AlternativeNptgLocalities" type="{http://www.naptan.org.uk/}NptgLocalityRefsStructure" minOccurs="0"/>
 *                   &lt;element name="MainNptgLocalities" type="{http://www.naptan.org.uk/}NptgLocalityRefsStructure" minOccurs="0"/>
 *                   &lt;element name="Suburb" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *                   &lt;element name="Town" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *                   &lt;element name="LocalityCentre" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="Location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.naptan.org.uk/}LocationStructure">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StopClassification" type="{http://www.naptan.org.uk/}StopClassificationStructure"/>
 *         &lt;element name="StopAreas" type="{http://www.naptan.org.uk/}StopAreaRefsStructure" minOccurs="0"/>
 *         &lt;element name="AdministrativeAreaRef" type="{http://www.naptan.org.uk/}AdministrativeAreaRefStructure"/>
 *         &lt;element name="PlusbusZones" type="{http://www.naptan.org.uk/}PlusbusZoneRefsStructure" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="StopAvailability" type="{http://www.naptan.org.uk/}StopValidityStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.naptan.org.uk/}RequiredModificationDetailsGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopPointStructure", propOrder = {
    "atcoCode",
    "naptanCode",
    "plateCode",
    "privateCode",
    "cleardownCode",
    "descriptor",
    "alternativeDescriptors",
    "place",
    "stopClassification",
    "stopAreas",
    "administrativeAreaRef",
    "plusbusZones",
    "notes",
    "stopAvailability"
})
public class StopPointStructure {

    @XmlElement(name = "AtcoCode", required = true)
    protected String atcoCode;
    @XmlElement(name = "NaptanCode")
    protected String naptanCode;
    @XmlElement(name = "PlateCode")
    protected String plateCode;
    @XmlElement(name = "PrivateCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String privateCode;
    @XmlElement(name = "CleardownCode")
    protected BigInteger cleardownCode;
    @XmlElement(name = "Descriptor", required = true)
    protected DescriptorStructure descriptor;
    @XmlElement(name = "AlternativeDescriptors")
    protected StopPointStructure.AlternativeDescriptors alternativeDescriptors;
    @XmlElement(name = "Place", required = true)
    protected StopPointStructure.Place place;
    @XmlElement(name = "StopClassification", required = true)
    protected StopClassificationStructure stopClassification;
    @XmlElement(name = "StopAreas")
    protected StopAreaRefsStructure stopAreas;
    @XmlElement(name = "AdministrativeAreaRef", required = true)
    protected AdministrativeAreaRefStructure administrativeAreaRef;
    @XmlElement(name = "PlusbusZones")
    protected PlusbusZoneRefsStructure plusbusZones;
    @XmlElement(name = "Notes")
    protected NaturalLanguageStringStructure notes;
    @XmlElement(name = "StopAvailability")
    protected StopValidityStructure stopAvailability;
    @XmlAttribute(name = "CreationDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification")
    protected ModificationEnumeration modification;
    @XmlAttribute(name = "RevisionNumber")
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "Status")
    protected StatusEnumeration status;

    /**
     * Gets the value of the atcoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtcoCode() {
        return atcoCode;
    }

    /**
     * Sets the value of the atcoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtcoCode(String value) {
        this.atcoCode = value;
    }

    /**
     * Gets the value of the naptanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaptanCode() {
        return naptanCode;
    }

    /**
     * Sets the value of the naptanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaptanCode(String value) {
        this.naptanCode = value;
    }

    /**
     * Gets the value of the plateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateCode() {
        return plateCode;
    }

    /**
     * Sets the value of the plateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateCode(String value) {
        this.plateCode = value;
    }

    /**
     * Gets the value of the privateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateCode() {
        return privateCode;
    }

    /**
     * Sets the value of the privateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateCode(String value) {
        this.privateCode = value;
    }

    /**
     * Gets the value of the cleardownCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCleardownCode() {
        return cleardownCode;
    }

    /**
     * Sets the value of the cleardownCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCleardownCode(BigInteger value) {
        this.cleardownCode = value;
    }

    /**
     * Gets the value of the descriptor property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptorStructure }
     *     
     */
    public DescriptorStructure getDescriptor() {
        return descriptor;
    }

    /**
     * Sets the value of the descriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptorStructure }
     *     
     */
    public void setDescriptor(DescriptorStructure value) {
        this.descriptor = value;
    }

    /**
     * Gets the value of the alternativeDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link StopPointStructure.AlternativeDescriptors }
     *     
     */
    public StopPointStructure.AlternativeDescriptors getAlternativeDescriptors() {
        return alternativeDescriptors;
    }

    /**
     * Sets the value of the alternativeDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPointStructure.AlternativeDescriptors }
     *     
     */
    public void setAlternativeDescriptors(StopPointStructure.AlternativeDescriptors value) {
        this.alternativeDescriptors = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link StopPointStructure.Place }
     *     
     */
    public StopPointStructure.Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPointStructure.Place }
     *     
     */
    public void setPlace(StopPointStructure.Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the stopClassification property.
     * 
     * @return
     *     possible object is
     *     {@link StopClassificationStructure }
     *     
     */
    public StopClassificationStructure getStopClassification() {
        return stopClassification;
    }

    /**
     * Sets the value of the stopClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopClassificationStructure }
     *     
     */
    public void setStopClassification(StopClassificationStructure value) {
        this.stopClassification = value;
    }

    /**
     * Gets the value of the stopAreas property.
     * 
     * @return
     *     possible object is
     *     {@link StopAreaRefsStructure }
     *     
     */
    public StopAreaRefsStructure getStopAreas() {
        return stopAreas;
    }

    /**
     * Sets the value of the stopAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopAreaRefsStructure }
     *     
     */
    public void setStopAreas(StopAreaRefsStructure value) {
        this.stopAreas = value;
    }

    /**
     * Gets the value of the administrativeAreaRef property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public AdministrativeAreaRefStructure getAdministrativeAreaRef() {
        return administrativeAreaRef;
    }

    /**
     * Sets the value of the administrativeAreaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public void setAdministrativeAreaRef(AdministrativeAreaRefStructure value) {
        this.administrativeAreaRef = value;
    }

    /**
     * Gets the value of the plusbusZones property.
     * 
     * @return
     *     possible object is
     *     {@link PlusbusZoneRefsStructure }
     *     
     */
    public PlusbusZoneRefsStructure getPlusbusZones() {
        return plusbusZones;
    }

    /**
     * Sets the value of the plusbusZones property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlusbusZoneRefsStructure }
     *     
     */
    public void setPlusbusZones(PlusbusZoneRefsStructure value) {
        this.plusbusZones = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setNotes(NaturalLanguageStringStructure value) {
        this.notes = value;
    }

    /**
     * Gets the value of the stopAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link StopValidityStructure }
     *     
     */
    public StopValidityStructure getStopAvailability() {
        return stopAvailability;
    }

    /**
     * Sets the value of the stopAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopValidityStructure }
     *     
     */
    public void setStopAvailability(StopValidityStructure value) {
        this.stopAvailability = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the modificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    /**
     * Sets the value of the modificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationEnumeration }
     *     
     */
    public ModificationEnumeration getModification() {
        if (modification == null) {
            return ModificationEnumeration.NEW;
        } else {
            return modification;
        }
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationEnumeration }
     *     
     */
    public void setModification(ModificationEnumeration value) {
        this.modification = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnumeration }
     *     
     */
    public StatusEnumeration getStatus() {
        if (status == null) {
            return StatusEnumeration.ACTIVE;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnumeration }
     *     
     */
    public void setStatus(StatusEnumeration value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Descriptor" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.naptan.org.uk/}DescriptorStructure">
     *                 &lt;attGroup ref="{http://www.naptan.org.uk/}RequiredModificationDetailsGroup"/>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descriptor"
    })
    public static class AlternativeDescriptors {

        @XmlElement(name = "Descriptor", required = true)
        protected List<StopPointStructure.AlternativeDescriptors.Descriptor> descriptor;

        /**
         * Gets the value of the descriptor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the descriptor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDescriptor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StopPointStructure.AlternativeDescriptors.Descriptor }
         * 
         * 
         */
        public List<StopPointStructure.AlternativeDescriptors.Descriptor> getDescriptor() {
            if (descriptor == null) {
                descriptor = new ArrayList<StopPointStructure.AlternativeDescriptors.Descriptor>();
            }
            return this.descriptor;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.naptan.org.uk/}DescriptorStructure">
         *       &lt;attGroup ref="{http://www.naptan.org.uk/}RequiredModificationDetailsGroup"/>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Descriptor
            extends DescriptorStructure
        {

            @XmlAttribute(name = "CreationDateTime", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creationDateTime;
            @XmlAttribute(name = "ModificationDateTime")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar modificationDateTime;
            @XmlAttribute(name = "Modification")
            protected ModificationEnumeration modification;
            @XmlAttribute(name = "RevisionNumber")
            protected BigInteger revisionNumber;
            @XmlAttribute(name = "Status")
            protected StatusEnumeration status;

            /**
             * Gets the value of the creationDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreationDateTime() {
                return creationDateTime;
            }

            /**
             * Sets the value of the creationDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreationDateTime(XMLGregorianCalendar value) {
                this.creationDateTime = value;
            }

            /**
             * Gets the value of the modificationDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getModificationDateTime() {
                return modificationDateTime;
            }

            /**
             * Sets the value of the modificationDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setModificationDateTime(XMLGregorianCalendar value) {
                this.modificationDateTime = value;
            }

            /**
             * Gets the value of the modification property.
             * 
             * @return
             *     possible object is
             *     {@link ModificationEnumeration }
             *     
             */
            public ModificationEnumeration getModification() {
                if (modification == null) {
                    return ModificationEnumeration.NEW;
                } else {
                    return modification;
                }
            }

            /**
             * Sets the value of the modification property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModificationEnumeration }
             *     
             */
            public void setModification(ModificationEnumeration value) {
                this.modification = value;
            }

            /**
             * Gets the value of the revisionNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRevisionNumber() {
                return revisionNumber;
            }

            /**
             * Sets the value of the revisionNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRevisionNumber(BigInteger value) {
                this.revisionNumber = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link StatusEnumeration }
             *     
             */
            public StatusEnumeration getStatus() {
                if (status == null) {
                    return StatusEnumeration.ACTIVE;
                } else {
                    return status;
                }
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link StatusEnumeration }
             *     
             */
            public void setStatus(StatusEnumeration value) {
                this.status = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NptgLocalityRef" type="{http://www.naptan.org.uk/}NptgLocalityRefStructure"/>
     *         &lt;element name="AlternativeNptgLocalities" type="{http://www.naptan.org.uk/}NptgLocalityRefsStructure" minOccurs="0"/>
     *         &lt;element name="MainNptgLocalities" type="{http://www.naptan.org.uk/}NptgLocalityRefsStructure" minOccurs="0"/>
     *         &lt;element name="Suburb" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
     *         &lt;element name="Town" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
     *         &lt;element name="LocalityCentre" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="Location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.naptan.org.uk/}LocationStructure">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nptgLocalityRef",
        "alternativeNptgLocalities",
        "mainNptgLocalities",
        "suburb",
        "town",
        "localityCentre",
        "location"
    })
    public static class Place {

        @XmlElement(name = "NptgLocalityRef", required = true)
        protected NptgLocalityRefStructure nptgLocalityRef;
        @XmlElement(name = "AlternativeNptgLocalities")
        protected NptgLocalityRefsStructure alternativeNptgLocalities;
        @XmlElement(name = "MainNptgLocalities")
        protected NptgLocalityRefsStructure mainNptgLocalities;
        @XmlElement(name = "Suburb")
        protected NaturalLanguagePlaceNameStructure suburb;
        @XmlElement(name = "Town")
        protected NaturalLanguagePlaceNameStructure town;
        @XmlElement(name = "LocalityCentre")
        protected Boolean localityCentre;
        @XmlElement(name = "Location", required = true)
        protected StopPointStructure.Place.Location location;

        /**
         * Gets the value of the nptgLocalityRef property.
         * 
         * @return
         *     possible object is
         *     {@link NptgLocalityRefStructure }
         *     
         */
        public NptgLocalityRefStructure getNptgLocalityRef() {
            return nptgLocalityRef;
        }

        /**
         * Sets the value of the nptgLocalityRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link NptgLocalityRefStructure }
         *     
         */
        public void setNptgLocalityRef(NptgLocalityRefStructure value) {
            this.nptgLocalityRef = value;
        }

        /**
         * Gets the value of the alternativeNptgLocalities property.
         * 
         * @return
         *     possible object is
         *     {@link NptgLocalityRefsStructure }
         *     
         */
        public NptgLocalityRefsStructure getAlternativeNptgLocalities() {
            return alternativeNptgLocalities;
        }

        /**
         * Sets the value of the alternativeNptgLocalities property.
         * 
         * @param value
         *     allowed object is
         *     {@link NptgLocalityRefsStructure }
         *     
         */
        public void setAlternativeNptgLocalities(NptgLocalityRefsStructure value) {
            this.alternativeNptgLocalities = value;
        }

        /**
         * Gets the value of the mainNptgLocalities property.
         * 
         * @return
         *     possible object is
         *     {@link NptgLocalityRefsStructure }
         *     
         */
        public NptgLocalityRefsStructure getMainNptgLocalities() {
            return mainNptgLocalities;
        }

        /**
         * Sets the value of the mainNptgLocalities property.
         * 
         * @param value
         *     allowed object is
         *     {@link NptgLocalityRefsStructure }
         *     
         */
        public void setMainNptgLocalities(NptgLocalityRefsStructure value) {
            this.mainNptgLocalities = value;
        }

        /**
         * Gets the value of the suburb property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguagePlaceNameStructure }
         *     
         */
        public NaturalLanguagePlaceNameStructure getSuburb() {
            return suburb;
        }

        /**
         * Sets the value of the suburb property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguagePlaceNameStructure }
         *     
         */
        public void setSuburb(NaturalLanguagePlaceNameStructure value) {
            this.suburb = value;
        }

        /**
         * Gets the value of the town property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguagePlaceNameStructure }
         *     
         */
        public NaturalLanguagePlaceNameStructure getTown() {
            return town;
        }

        /**
         * Sets the value of the town property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguagePlaceNameStructure }
         *     
         */
        public void setTown(NaturalLanguagePlaceNameStructure value) {
            this.town = value;
        }

        /**
         * Gets the value of the localityCentre property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLocalityCentre() {
            return localityCentre;
        }

        /**
         * Sets the value of the localityCentre property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLocalityCentre(Boolean value) {
            this.localityCentre = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link StopPointStructure.Place.Location }
         *     
         */
        public StopPointStructure.Place.Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopPointStructure.Place.Location }
         *     
         */
        public void setLocation(StopPointStructure.Place.Location value) {
            this.location = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.naptan.org.uk/}LocationStructure">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Location
            extends LocationStructure
        {


        }

    }

}
