//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimingStatusEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimingStatusEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="PPT"/>
 *     &lt;enumeration value="principlePoint"/>
 *     &lt;enumeration value="TIP"/>
 *     &lt;enumeration value="timeInfoPoint"/>
 *     &lt;enumeration value="PTP"/>
 *     &lt;enumeration value="principleTimingPoint"/>
 *     &lt;enumeration value="OTH"/>
 *     &lt;enumeration value="otherPoint"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimingStatusEnumeration")
@XmlEnum
public enum TimingStatusEnumeration {


    /**
     * Principal Point. This stop is part of the service registration and is liable to inspections and enforcement.
     * 
     */
    PPT("PPT"),
    @XmlEnumValue("principlePoint")
    PRINCIPLE_POINT("principlePoint"),

    /**
     * Time Info Point. This stop is not part of the service registration and is not liable to inspections or enforcement, however it is expected to be used within a timetable to identify a timing point which will not be a Principal Point.
     * 
     */
    TIP("TIP"),
    @XmlEnumValue("timeInfoPoint")
    TIME_INFO_POINT("timeInfoPoint"),

    /**
     * Principal and Time Info Point. This stop is a Principal Point which is expected to be also used as a timing point within a timetable.
     * 
     */
    PTP("PTP"),
    @XmlEnumValue("principleTimingPoint")
    PRINCIPLE_TIMING_POINT("principleTimingPoint"),

    /**
     * Other Bus Stop. This stop is not part of the service registration and is not liable to inspections or enforcement; it is not expected to be used as part of the timetable.
     * 
     */
    OTH("OTH"),
    @XmlEnumValue("otherPoint")
    OTHER_POINT("otherPoint");
    private final String value;

    TimingStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimingStatusEnumeration fromValue(String v) {
        for (TimingStatusEnumeration c: TimingStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
