//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.09 at 02:09:56 PM CEST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UkLanguageEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UkLanguageEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="CY"/>
 *     &lt;enumeration value="GA"/>
 *     &lt;enumeration value="GD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UkLanguageEnumeration")
@XmlEnum
public enum UkLanguageEnumeration {


    /**
     * English.
     * 
     */
    EN,

    /**
     * Welsh.
     * 
     */
    CY,

    /**
     * Irish.
     * 
     */
    GA,

    /**
     * Scots Gaelic.
     * 
     */
    GD;

    public String value() {
        return name();
    }

    public static UkLanguageEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
